---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - typescript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
- dist/
- test/
- build/
- docs/
- examples/
plugins:
  tslint:
    enabled: true
    config: tslint.json
