language: node_js
before_script: [
    "npm i"
  ]
node_js:
  - '0.10'
  - '0.12'
  - '4.2'
  - '5'
  - '6'
notifications:
  email: false
script: mocha --compilers js:babel-core/register ./test/**/*.spec.js
os: "linux"